

"""
This module bridges the new prediction pipeline with the diagnostics used to analyse the inherited model. It reformats the wide, daily forecast outputs generated by the new model into the long, hourly format required by the old evaluation functions. 

"""


from __future__ import annotations
from pathlib import Path
from typing import Dict, Optional, Sequence, Tuple
from datetime import datetime,timezone
import json
import pandas as pd
from src.config import ZoneConfig

# The two old diagnostic modules are reused UNCHANGED.
from src.diagnostics_part1 import run_full_diagnostic, cross_zone_comparison
from src.diagnostics_part2 import run_part2_diagn, _spike_threshold_per_zone


# Column conventions emitted by model.predict_fold (the new pipeline).
HOUR_COLS: list[str] = [f"h{h:02d}" for h in range(24)]          # actuals
PRED_COLS: list[str] = [f"pred_h{h:02d}" for h in range(24)]     # predictions
REGIME_COL: str = "effective_regime"                             # 0=A, 1=B, 2=C0, 3=C1

# For readability when reading the printed "Cluster N" rows.
REGIME_LABELS: Dict[int, str] = {0: "A (negative)", 1: "B (spike)", 2: "C0", 3: "C1"}



# ##############################################################################
# WIDE  ->  LONG
# ##############################################################################

def to_long_predictions(
    df_preds: pd.DataFrame,
    zone_cfg: ZoneConfig,
    te_start: Optional[str] = None,
    te_end: Optional[str] = None,
) -> pd.DataFrame:
    """Reshape the new pipeline's wide daily predictions into one row per hour.

    Builds a tz-naive UTC hourly timestamp from each day's `date` plus the hour
    index parsed from the h00..h23 / pred_h00..pred_h23 columns. UTC hours match
    the old diagnostics, which also treated h00..h23 as UTC.

    Args:
        df_preds: Output of `load_or_train` / `walk_forward`. Must contain `date`,
            `h00..h23`, `pred_h00..pred_h23`, and `effective_regime`.
        zone_cfg: Zone configuration; only `zone_cfg.zone` is used (the `zone`
            column label so the Part 2 plots colour the series correctly).
        te_start: Optional inclusive lower bound on the day, e.g. "2025-06-18".
        te_end: Optional inclusive upper bound on the day, e.g. "2025-11-26".

    Returns:
        Long DataFrame sorted by time with columns:
            date_time | zone | actual | predicted | cluster
        where `cluster` carries `effective_regime` as an int .
    """
    df = df_preds.copy()

    # Normalise `date` to a tz-naive day, regardless of whether it arrives
    # tz-aware (df_daily is UTC-indexed) or already naive.
    day = pd.to_datetime(df["date"])
    if getattr(day.dt, "tz", None) is not None:
        day = day.dt.tz_convert("UTC").dt.tz_localize(None)
    df["_day"] = day.dt.normalize()

    # Restrict to the matched comparison window (inclusive on both ends, so the
    # final day's full 24 hours are kept - matching the old test set).
    if te_start is not None:
        df = df[df["_day"] >= pd.Timestamp(te_start)]
    if te_end is not None:
        df = df[df["_day"] <= pd.Timestamp(te_end)]

    if df.empty:
        raise ValueError(
            f"No predictions in window [{te_start}, {te_end}] for {zone_cfg.zone}. "
            f"Check that df_preds covers this fold."
        )

    regime = (
        df[REGIME_COL].astype("Int64")
        if REGIME_COL in df.columns
        else pd.Series(pd.NA, index=df.index, dtype="Int64")
    )
    base = pd.DatetimeIndex(df["_day"]).tz_localize("UTC")

    frames = []
    for h in range(24):
        ts = (base + pd.Timedelta(hours=h)).tz_localize(None)  # naive UTC instant
        frames.append(
            pd.DataFrame(
                {
                    "date_time": ts.to_numpy(),
                    "zone": zone_cfg.zone,
                    "actual": df[f"h{h:02d}"].to_numpy(dtype=float),
                    "predicted": df[f"pred_h{h:02d}"].to_numpy(dtype=float),
                    "cluster": regime.to_numpy(),
                }
            )
        )

    long_df = (
        pd.concat(frames, ignore_index=True)
        .sort_values("date_time")
        .reset_index(drop=True)
    )
    return long_df




# ##############################################################################
#  LONG  ->  OLD-MODULE INPUT CONTRACTS
# ##############################################################################

def build_part1_inputs(long_df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Build the (pred_df, cluster_df) pair that `run_full_diagnostic` expects.

    `run_full_diagnostic` reads pred_df["date"] as an *hourly* timestamp (it calls
    `.dt.hour` on it) and then overwrites it with a day string to merge cluster_df.
    So pred_df["date"] must carry the hour, and cluster_df["date"] must be
    "%Y-%m-%d" day strings with one regime per day.

    Args:
        long_df: Output of `to_long_predictions`.

    Returns:
        pred_df with columns `date` (hourly ts), `price_eur_mwh` (actual),
        `weighted_pred_price` (predicted); and cluster_df with columns
        `date` (day string), `cluster` (int regime id).
    """
    pred_df = pd.DataFrame(
        {
            "date": long_df["date_time"],            # hourly timestamp
            "price_eur_mwh": long_df["actual"],      # actual  (old column name)
            "weighted_pred_price": long_df["predicted"],  # predicted (old column name)
        }
    )

    cluster_df = (
        long_df.assign(
            date=pd.to_datetime(long_df["date_time"]).dt.strftime("%Y-%m-%d")
        )
        .dropna(subset=["cluster"])
        .groupby("date", as_index=False)["cluster"]
        .first()
    )
    cluster_df["cluster"] = cluster_df["cluster"].astype(int)
    return pred_df, cluster_df


def build_part2_input(long_df: pd.DataFrame) -> pd.DataFrame:
    """Return the diag_df that `run_part2_diagn` expects.

    `_prepare` requires {date_time, zone, actual, predicted}; `cluster` is carried
    through for parity with the old diag_df but is not strictly required.

    Args:
        long_df: Output of `to_long_predictions`.

    Returns:
        diag_df with columns date_time | zone | actual | predicted | cluster.
    """
    return long_df[["date_time", "zone", "actual", "predicted", "cluster"]].copy()


def save_diagnostic_inputs(df_preds, zone_cfg, te_start, te_end, out_dir):
    """Reshape the matched-fold predictions to long and persist them for the
    multi-zone diagnostics notebook. Writes {zone}.parquet + {zone}_meta.json."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    long_df = to_long_predictions(df_preds, zone_cfg, te_start, te_end)

    path = out_dir / f"{zone_cfg.zone}.parquet"
    long_df.to_parquet(path, index = False) # save as parquet because it preserves the UTC datetime

    meta = {
        "zone" : zone_cfg.zone,
        "te_start": str(te_start),
        "te_end": str(te_end),
        "n_hours": int(len(long_df)),
        "n_days": int(long_df["date_time"].dt.floor("D").nunique()),
        "saved_at": datetime.now(timezone.utc).isoformat(timespec = "seconds"),
    }

    (out_dir / f"{zone_cfg.zone}_meta.json").write_text(json.dumps(meta, indent = 2))

    print(f"[{zone_cfg.zone}] saved {meta['n_hours']} h "
          f"({meta['te_start']} -> {meta['te_end']}) to {path}")
    return path

def load_diagnostic_inputs(input_dir, zones):
    """Load each zone's saved long frame into {zone: DataFrame}."""
    input_dir = Path(input_dir)
    long_by_zone = {}
    for z in zones:
        p = input_dir / f"{z}.parquet"
        if not p.exists():
            raise FileNotFoundError (f"Missing diagnostic input for {z} : {p}")
        
        df = pd.read_parquet(p)
        df["date_time"] = pd.to_datetime(df["date_time"])
        long_by_zone[z] = df
    return long_by_zone

def run_multizone_diagnostics(
        long_by_zone, save_dir, *, price_floor = 10.0, tag = "_new",
        spike_quantile = 0.95, near_zero_upper = 20.0, thresholds = (-10, -20, -50)
):
    """Run Part 1 (per-zone + cross-zone) and Part 2 (stacked) old diagnostics."""
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok= True)

    diag_df = pd.concat(
        [build_part2_input(df) for df in long_by_zone.values()],
        ignore_index=True
    )

   

    summaries = {}
    for zone,df in long_by_zone.items():
        pred_df, cluster_df = build_part1_inputs(df)
        summaries[zone] = run_full_diagnostic(
            pred_df, cluster_df, f"{zone}{tag}" , price_floor
        )

    
    p2_out = run_part2_diagn(
        diag_df, spike_quantile=spike_quantile, near_zero_upper=near_zero_upper, 
        thresholds=list(thresholds), save_dir=str(save_dir)
    )
    
    cross = cross_zone_comparison(summaries)

    return {"diag_df": diag_df, "p2_out": p2_out, "summaries": summaries, "cross_zone": cross}









# ##############################################################################
#   CONVENIENCE - run both old diagnostic suites in one call
# ##############################################################################

def run_comparison_diagnostics(
    df_preds: pd.DataFrame,
    zone_cfg: ZoneConfig,
    save_dir: str | Path,
    *,
    te_start: Optional[str] = None,
    te_end: Optional[str] = None,
    price_floor: float = 10.0,
    tag: str = "_new",
    spike_quantile: float = 0.95,
    near_zero_upper: float = 20.0,
    thresholds: Sequence[int] = (-10, -20, -50),
) -> Dict[str, object]:
    """Run Part 1 + Part 2 of the old diagnostics on new-pipeline predictions.

    Part 1 prints the breakdown table and writes `diagnostic_{zone}{tag}.png` to
    the current working directory (the old module hard-codes that path; `tag`
    keeps it from overwriting the saved old artefact). Part 2 writes its four
    figures into `save_dir`.

    Args:
        df_preds: New-pipeline predictions (ideally already the single fold that is the same as the old group's fold).
        zone_cfg: Zone configuration for the bidding zone being run.
        save_dir: Directory for the Part 2 PNGs (created if absent).
        te_start, te_end: Inclusive day bounds of the matched comparison window.
            Pass them even if df_preds is already the single fold - explicit is safer.
        price_floor: WAPE clamping floor (δ); 10 EUR/MWh matches the old report.
        tag: Suffix appended to the zone label so Part 1's figure/title don't
            collide with the saved old run.
        spike_quantile, near_zero_upper, thresholds: Passed straight through to the
            old modules; keep them identical to whatever produced the old results.

    Returns:
        Dict with keys: `long` (the reshaped frame), `summary` (Part 1 breakdown
        DataFrame), `p2_out` (Part 2 return dict), `diag_df` (the Part 2 input).
    """
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    long_df = to_long_predictions(df_preds, zone_cfg, te_start, te_end)
    pred_df, cluster_df = build_part1_inputs(long_df)
    diag_df = build_part2_input(long_df)

    # Part 1 - breakdown table + four-panel figure (identical code to the old run).
    summary = run_full_diagnostic(
        pred_df, cluster_df, f"{zone_cfg.zone}{tag}", price_floor
    )

    # Part 2 - hourly bias, intraday_residual_by_bucket, spike hit-rate, weekday/weekend.
    p2_out = run_part2_diagn(
        diag_df,
        spike_quantile=spike_quantile,
        near_zero_upper=near_zero_upper,
        thresholds=list(thresholds),
        save_dir=str(save_dir),
    )

    return {"long": long_df, "summary": summary, "p2_out": p2_out, "diag_df": diag_df}


# ##############################################################################
# WAPE inflation check  (Section 7-F of the old notebook)
# ##############################################################################

def wape_inflation_report(
    summary: pd.DataFrame,
    threshold_pp: float = 20.0,
) -> pd.DataFrame:
    """Return slices where raw WAPE exceeded clamped WAPE by > threshold_pp points.

    A large gap means the raw WAPE metric was inflated by near-zero / negative
    actual prices in that slice - i.e. the failure is partly a metric problem.
    This reproduces the old notebook's Section 7-F check on the `summary` table
    returned by `run_full_diagnostic`.

    Args:
        summary: Breakdown DataFrame from `run_full_diagnostic`.
        threshold_pp: Minimum (wape - wape_cl) gap, in percentage points.

    Returns:
        Filtered, sorted DataFrame of the inflated slices.
    """
    df = summary.copy()
    df["wape_inflation"] = df["wape"] - df["wape_cl"]
    inflated = df[df["wape_inflation"] > threshold_pp]
    cols = ["dimension", "group", "n_hours", "wape", "wape_cl", "wape_inflation"]
    return inflated[cols].sort_values("wape_inflation", ascending=False).reset_index(drop=True)


